### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by JGAntunes** [CodeFoodPixels/netlify-plugin-webmentions#1]
Hey @CodeFoodPixels, as per https://github.com/netlify/plugins/pull/225 we'll be droping some reviews in your repo, hope you don't mind.

Currently it seems like the way errors coming from the `wm` event emitter are handled is by calling `utils.build.failPlugin` directly:
https://github.com/CodeFoodPixels/netlify-plugin-webmentions/blob/16751c1ce0a8c704bc9236d8779bec326e548700/index.js#L34

Under the hood `utils.build.failPlugin` is actually throwing an exception. So, the fact that this is being called from a callback of an event handler could potentially trigger some unwanted unexpected behaviour (such as halting the plugin process with an unhandled exception).

We would like to suggest using something like:
```js
try {
    await new Promise((resolve, reject) => {
      (...)

      const wm = new Webmention({ limit, send: true });

      wm.on("error", (e) => reject(e));

      wm.on("sent", (res) => {
        (..)
      });

      wm.on("end", () => {
        resolve();
      });

      wm.fetch(feedUrl);
    });
} catch (error) {
  utils.build.failPlugin(error)
}
```

**Comment by CodeFoodPixels** [comment]
Cool, thanks! I've updated this in 725a0f7417ecc31e6b211117412795555c108e82.

**Comment by JGAntunes** [comment]
Awesome 👍
